apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejsapp
  name: nodejsapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - image: localhost:5001/nodejsapp:0.1.0
        imagePullPolicy: Always
        name: node
        env: 
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 3000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000